# -*- coding: utf-8 -*-
"""BryanRflyX2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BiSbnc2ADI-LXNXTaJNER7HKG7OXhYkA
"""

data = [10, 9, 7, 8, 10, 8]
data[2] = 50
print(data)

data = [10, 9, 7, 8, 10, 8]
print(data)
data.append(15)
print(data)

import pandas
data = [76, 90, 85, 78, 100, "88"]
siswa = ["susi", "Hana", "April", "Yolla", "Ahmad", "Tika"]
hasil = ["TT/R", "T/P", "T/P", "TT/R", "T/P", "T/P"]
nilai = pandas.DataFrame({
    "hasil": siswa,
    "nilai": data,
    "ket": hasil
})
nilai

import requests 
import pandas as pd
from bs4 import BeautifulSoup

th="https://www.jobs.id/lowongan-kerja?kata-kunci-part time" 
halaman = requests.get(th) 
hasil = BeautifulSoup(halaman.content, 'html.parser')
lowkers = hasil.find_all(class_="single-job-ads")

posisi = []
instansi = []
gaji = []

for p in lowkers:
  t1 = p.select("h3")
  t2 = t1[0].select("a")
  posisi.append(t2[0].get_text())

  t1 = p.select("p")
  t2 = t1[0].select("a")

  try:
    instanasi.append(t2[0].get_text())
  except:
      instansi.append("-")

      t2 = t1[1].select("span")

  try:
      gaji.append(t2[1].get_text())
  except:
        gaji.append(t2[0].get_text())

print(posisi)
print(instansi)
print(gaji)

import requests 
import pandas as pd
from bs4 import BeautifulSoup

th="https://www.jobs.id/lowongan-kerja?kata-kunci-part time"
halaman = requests.get(th)
hasil = BeautifulSoup(halaman.content, 'html.parser')
lowkers = hasil.find_all(class_="single-job-ads")

posisi = []
instansi = []
gaji = []
alamat = []

for p in lowkers:
  t1 = p.select("h3")
  t2 = t1[0].select("a")
  posisi.append(t2[0].get_text())

  t1 = p.select("p")
  t2 = t1[0].select("a")

  try:
    instanasi.append(t2[0].get_text())
  except:
      instansi.append("-")

      t2 = t1[1].select("span")

  try:
      gaji.append(t2[1].get_text())
  except:
        gaji.append(t2[0].get_text())
  try:
      alamat.append(t1[0].get_text())
  except:
        alamat.append(t1[0].get_text())

lowker = pd.DataFrame({
     "Posisi": posisi,
     "Instansi": instansi,
     "Gaji": gaji,
     "Alamat": alamat

})

lowker

import requests 
import pandas as pd
from bs4 import BeautifulSoup

url ="https://www.merdeka.com/peristiwa"
halaman = requests.get(url)
hasil = BeautifulSoup(halaman.content, 'html.parser')
news = hasil.find_all(class_="meta-content")

  
berita = []


for a in news:
    b1 = a.select("h3")
    b2 = b1[0].select("a")
    berita.append(b2[0].get_text()); 
 
print(berita)

import requests 
import pandas as pd
from bs4 import BeautifulSoup

url ="https://www.merdeka.com/uang"
halaman = requests.get(url)
hasil = BeautifulSoup(halaman.content, 'html.parser')
news = hasil.find_all(class_="meta-content")

  
berita = []


for a in news:
    b1 = a.select("h3")
    b2 = b1[0].select("a")
    berita.append(b2[0].get_text()); 
 
print(berita)

import requests 
import pandas as pd
from bs4 import BeautifulSoup

th="https://www.jobs.id/lowongan-kerja?kata-kunci-part time"
halaman = requests.get(th)
hasil = BeautifulSoup(halaman.content, 'html.parser')
lowkers = hasil.find_all(class_="single-job-ads")

posisi = []
instansi = []
gaji = []

for p in lowkers:
  t1 = p.select("h3")
  t2 = t1[0].select("a")
  posisi.append(t2[0].get_text())

  t1 = p.select("p")
  t2 = t1[0].select("a")

  try:
    instanasi.append(t2[0].get_text())
  except:
      instansi.append("-")
      t2 = t1[1].select("span")
      try:
        xgaji = t2[1].get_text()
      except:
        xgaji = t2[0].get_text()
      xgaji = xgaji.replace(".","")
      if (xgaji=="Gaji Dirahasiakan"):
        xgaji = 0
      gaji.append(xgaji); 

  try:
      gaji.append(t2[1].get_text())
  except:
        gaji.append(t2[0].get_text())

 lowker = pd.DataFrame({
     "Posisi": posisi, 
     "Instansi": instansi,
     "Gaji": gaji
 })

fig = px.bar(lowker, x='Instansi', y='Gaji')
fig.show()